apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dot-141024
  janus-idp.io/tekton: dot-141024
  backstage.io/kubernetes-id: dot-141024
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dot-141024
resources:
- deployment.yaml
- route.yaml
- service.yaml
