apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dot-141024
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dot-141024 
  name: dot-141024
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dot-141024
    weight: 100 
